version: 2
jobs:
  build-binary:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: .circleci/build-binary.sh
      - store_artifacts:
          path: /tmp/artifacts
  build-docker-image:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image.sh

workflows:
  version: 2
  build:
    jobs:
      - build-binary
      - build-docker-image
