version: 2
jobs:
  build-binary:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: .circleci/build-binary.sh
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - logfwd
  build-docker-image:
    docker:
      - image: docker:18
    working_directory: /build
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /build
      - run: .circleci/build-docker-image.sh

workflows:
  version: 2
  build:
    jobs:
      - build-binary
      - build-docker-image:
          requires:
            - build-binary
