version: 2
jobs:
  get-version:
    docker:
      - image: habx/devops-build-infos
    working_directory: /work
    steps:
      - checkout
      - run: /build/run.sh
      - run: cat version.txt build.json
      - persist_to_workspace:
          root: /work
          paths:
            - version.txt
            - build.json
  build-binary:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cp /tmp/workspace/version.txt .
      - run: .circleci/build-binary.sh
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - logfwd
  linting:
    docker:
      - image: circleci/golang:1.11 # golang:1.11 #golangci/golangci-lint:v1.10
    steps:
      - checkout
      - run: .circleci/linting.sh
  build-docker-image:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - setup_remote_docker
      - run: .circleci/build-docker-image.sh

workflows:
  version: 2
  build:
    jobs:
      - linting
      - get-version:
          filters:
            tags:
              only: /^v[0-9.]+$/
      - build-binary:
          requires:
            - get-version
          filters:
            tags:
              only: /^v[0-9.]+$/
      - build-docker-image:
          requires:
            - build-binary
          filters:
            tags:
              only: /^v[0-9.]+$/
